name: Index pages

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  index-pages:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Run index
        uses: ./
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}

      - name: Push New Index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[workflow]: Update indexes" || echo "No changes to commit"
          git push
